// 전체 앱에서 사용하는 경로 상수입니다.
// 문자열 경로를 여러 파일에 직접 쓰지 않도록 한곳에서 관리합니다.
export const ROUTES = {
  login: '/login',
  passwordReset: '/login/password-reset',
  authRoute: '/auth/route',
  sessionExpired: '/session-expired',
  forbidden: '/403',
  publicCertificateVerify: '/verify/:publicToken',
  studentDashboard: '/student/dashboard',
  studentCourse: '/student/course',
  studentCourseMaterials: '/student/course/materials',
  studentCourseAssignments: '/student/course/assignments',
  studentCourseAssignmentDetail: '/student/course/assignments/:assignmentId',
  studentQuizzes: '/student/quizzes',
  studentQuizTake: '/student/quizzes/:quizId/take',
  studentQuizResult: '/student/quizzes/:quizId/result',
  studentProfile: '/student/profile',
  studentOnboarding: '/student/onboarding',
  studentAttendance: '/student/attendance',
  studentAttendanceForm: '/student/attendance/form',
  studentRecords: '/student/records',
  studentRecordNew: '/student/records/new/:recordType',
  studentBlogRecordDetail: '/student/records/blog/:recordId',
  studentBlogRecordEdit: '/student/records/blog/:recordId/edit',
  studentCertificate: '/student/certificate',
  studentCertificateChangesRequested: '/student/certificate/changes-requested',
  studentCertificatePublication: '/student/certificate/publication',
  studentProjects: '/student/projects',
  studentProjectsNew: '/student/projects/new',
  studentProjectWorkspace: '/student/projects/:projectId',
  studentProjectChangeRequest: '/student/projects/:projectId/change-requests/new',
  studentTroubleshooting: '/student/troubleshooting',
  studentTroubleshootingNew: '/student/troubleshooting/new',
  studentTroubleshootingChangeRequest: '/student/troubleshooting/:id/change-requests/new',
  studentPeerEvaluations: '/student/peer-evaluations',
  studentPeerReview: '/student/peer-review',
  studentPeerTag: '/student/peer-tag',
  studentPeerReputation: '/student/peer-reputation',
  studentMileage: '/student/mileage',
  studentMileageProducts: '/student/mileage/products',
  studentMileageHistory: '/student/mileage/history',
  studentPlay: '/student/play',
  studentPlayTyping: '/student/play/typing',
} as const
